### ISSUE TITLE
haml/slim support

### ISSUE THREAD

**Issue by tkellen** [jeremyevans/forme#1]
Any chance you'll be adding this to the forme/sinatra at some point?  I've been tinkering a bit, but I'm new to ruby and I haven't had much luck making it happen.

Thanks a million!

**Comment by tmsrjs** [comment]
@tkellen @jeremyevans I know it's been a while but this works perfectly for haml:
```haml
-#app/views/forms/_some_partial.html.haml
= Forme::Rails::Form.form({ action: '/foo' }, template: self) do |f|
  %fieldset
    = f.input :text, name: 'foo', value: 'bar'
```
