### ISSUE TITLE
Form method optional

### ISSUE THREAD

**Issue by sts** [jeremyevans/forme#119]
When using hypertext libraries such as htmx.org you might not want to [set a method on a form](https://htmx.org/docs/#synchronization). 

Currently the method field seems to be mandatory:

```ruby
form(@settings, { method: "" }, {})
```

**Comment by jeremyevans** [comment]
The method attribute is not mandatory.  If you look at most of Forme's specs in spec/forme_spec.rb, they don't set a method attribute.  Is there something in the documentation that implies the method attribute is required (if so, it should be fixed)?

**Comment by sts** [comment]
I'm using the Roda helper and it's adding the `method` attribute regardless if I specify it or not. It will default to `post`, if no `method` parameter is supplied to `form`.

**Comment by sts** [comment]
After further debugging, this is a no issue! Sorry!
