### ISSUE TITLE
Doc change?

### ISSUE THREAD

**Issue by joep** [jeremyevans/forme#18]
In the section for usage (https://github.com/jeremyevans/forme#usage) the method for creating the form is named 'show_form' but in the discussion that follows it is referred to as 'album_form'. Obviously not a big deal, but a little confusing on my read through.

**Comment by jeremyevans** [comment]
Thanks for letting me know. You are correct, that is a documentation bug, I'll fix it in a couple days.

**Comment by joep** [comment]
Great, thanks.

Is it possible there also an issue with the documentation of 'Forme.register_transformer'?

As described (Forme.register_transformer(:wrapper, :p){|t| t.tag(:p, {}, t)}) does not appear to work. First, it seems to have two arguments (tag, form) to the block and second, returning a tag results in an infinite loop. But perhaps there is some setting I overlooked.

**Comment by joep** [comment]
Thanks.

There is also (or at least I think there is after playing around a bit) a problem with the sample wrapper:

    Forme.register_transformer(:wrapper, :p){|t| t.tag(:p, {}, t)}

This issue is that if you have a helper or error, e.g.,
   f.input :when, :error => 'aaa', :help => 'bbb'
 then parameter t is an array and the transformer fails.

**Comment by jeremyevans** [comment]
Thanks for the feedback.  I've updated the README to fix the example code for register_transformer, as well as give a better explanation.
