### ISSUE TITLE
Support for Rack::MethodOverride

### ISSUE THREAD

**Issue by janko-m** [jeremyevans/forme#22]
Hey Jeremy,

I read your comment in https://github.com/jeremyevans/forme/issues/5#issuecomment-27158269, but I was wondering if you'd still be open to adding support for the `_method` hidden field that's detected by the `Rack::MethodOverride` middleware. For me that's a perfectly acceptable way of working around HTML forms not supporting other HTTP verbs like PUT or PATCH, without having to resort to using JavaScript.

I'm not sure what would be the best way to support this. My initial idea was to check whether form's `:action` was set to something other than `get` or `post`, and in that case set `action="post"` and add the hidden field indicating the HTTP verb is actually `put`. However, I can imagine someone relying on the behaviour that `action: "put"` would actually add `action="put"`, and then they might be handling these forms via JavaScript.

Another idea was adding a `:method_override` option on the form, which could be set to `true` to enable this behaviour. In this case it would be nice if this option could be set as the default. If you would accept this, I could send a PR.

**Comment by jeremyevans** [comment]
You can add a hidden input to the form:

```
  f.input(:hidden, :name=>'_method', :value=>'PUT')
```

It's probably possible to make that the default behavior by using a subclass or your own method.

I don't want to add direct support for Rack::MethodOverride, I consider it a bad hack.  Applications targetting browsers should limit their HTTP methods to GET and POST.
