### ISSUE TITLE
Default label for hidden fields

### ISSUE THREAD

**Issue by janko-m** [jeremyevans/forme#23]
I noticed that `f.input :hidden` automatically adds a label, but I don't think there is any scenario in which you might want to have a label for a hidden field. What do you think about changing Forme to omit labels for hidden fields by default?

**Comment by jeremyevans** [comment]
That's weird, f.input :hidden shouldn't add a label unless you specify a :label option, and it wouldn't make sense to specify one. for a hidden input.  I see in the other pull request that you only want to do this for the Sequel plugin, and that makes sense.  I'm going to close this pull request, but omitting labels for hidden inputs in the Sequel plugin should be fine.

**Comment by janko-m** [comment]
Oh, yeah, I meant only for the Sequel plugin which is the one that adds labels by default. Thanks for merging this and the rest of the pull requests!
